# Generated by Django 4.0.4 on 2022-06-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_current_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='has_voted',
            field=models.BooleanField(default=False),
        ),
    ]
